<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
	<xacro:property name="PI" value="3.1415927" />
	<xacro:property name="radius" value="0.03" />
	<myUsePropertyxxx name="${PI}" />
	<myUsePropertyxxx name="${radius}" />

	<myUsePropertyYyy result="${PI / 2}" />
	<myUsePropertyYyy result="${radius * 2}" />


</robot>
