<robot name="mark_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="PI" value="3.1415926" />
	<material name="black">
		<color rgba="0.0 0.0 0.0 1.0" />
	</material>
	<xacro:property name="base_length" value="0.2" />
	<xacro:property name="base_width" value="0.15" />
	<xacro:property name="base_height" value="0.08" />
	<xacro:property name="footprint_radius" value="0.001" />
	<xacro:property name="earth_space" value="0.015" />
	<xacro:property name="base_mass" value="0.5" />

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<material name="yellow">
				<color rgba="0.5 0.3 0.0 0.5" />
			</material>
		</visual>
		<collision>
			<geometry>
				<box size="${base_length} ${base_width} ${base_height}" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0" />
		</collision>
		<xacro:Box_inertial_matrix m="${base_mass}" w="${base_width}" l="${base_length}" h="${base_height}" />
	</link>

	<link name="base_footprint">
		<visual>
			<geometry>
				<sphere radius="${footprint_radius}" />
			</geometry>
		</visual>
	</link>
	<joint name="base_link2base_footprint" type="fixed">
		<parent link="base_footprint" />
		<child link="base_link" />
		<origin xyz="0 0 ${earth_space + base_height / 2}" />
	</joint>
	<gazebo reference="base_link">
		<material>Gazebo/Yellow</material>
	</gazebo>

	<xacro:property name="wheel_radius" value="0.0325" />
	<xacro:property name="wheel_length" value="0.015" />
	<xacro:property name="wheel_mass" value="0.05" />
	<xacro:macro name="add_wheels" params="name flag1 flag2">
		<link name="${name}_wheel">
			<visual>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}" />
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
				<material name="black" />
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${wheel_radius}" length="${wheel_length}" />
				</geometry>
				<origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
			</collision>
			<xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
		</link>
		
		<joint name="${name}_wheel2base_link" type="continuous">
			<parent link="base_link" />
			<child link="${name}_wheel" />
			<origin xyz="${flag1 * base_length / 2} ${flag2 * base_width / 2} ${-(earth_space + base_height / 2 - wheel_radius) }" />
			<axis xyz="0 1 0" />
		</joint>

		<gazebo reference="${name}_wheel">
			<material>Gazebo/Red</material>
		</gazebo>
	</xacro:macro>

	<xacro:add_wheels name="front_left" flag1="1" flag2="1" />
	<xacro:add_wheels name="back_left" flag1="1" flag2="-1" />
	<xacro:add_wheels name="front_right" flag1="-1" flag2="1" />
	<xacro:add_wheels name="back_right" flag1="-1" flag2="-1" />
	
</robot>
