<robot name="mark_move" xmlns:xacro="http://wiki.ros.org/xacro">

	<!-- 传动实现:用于连接控制器与关节 -->
	<xacro:macro name="joint_trans" params="joint_name">
	<!-- Transmission is important to link the joints and the controller -->
	<transmission name="${joint_name}_trans">
	    <type>transmission_interface/SimpleTransmission</type>
	    <joint name="${joint_name}">
		<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
	    </joint>
	    <actuator name="${joint_name}_motor">
		<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
	    </actuator>
	</transmission>
	</xacro:macro>

	<!-- 每一个驱动轮都需要配置传动装置 -->
	<xacro:joint_trans joint_name="front_left_wheel2base_link" />
	<xacro:joint_trans joint_name="back_left_wheel2base_link" />
	<xacro:joint_trans joint_name="front_right_wheel2base_link" />
	<xacro:joint_trans joint_name="back_right_wheel2base_link" />

	<gazebo>
		<plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<updateRate>100.0</updateRate>
			<robotNamespace>/</robotNamespace>
			<leftFrontJoint>front_left_wheel2base_link</leftFrontJoint>
			<rightFrontJoint>front_right_wheel2base_link</rightFrontJoint>
			<leftRearJoint>back_left_wheel2base_link</leftRearJoint>
			<rightRearJoint>back_right_wheel2base_link</rightRearJoint>
			<wheelSeparation>${base_width}</wheelSeparation>
			<wheelDiameter>${wheel_radius * 2}</wheelDiameter>
			<robotBaseFrame>base_footprint</robotBaseFrame>
	 		<torque>2</torque>
			<topicName>cmd_vel</topicName>
			<broadcastTF>1</broadcastTF>
			<wheelAcceleration>1.8</wheelAcceleration>
			<commandTopic>cmd_vel</commandTopic>
			<odometryFrame>odom</odometryFrame>
			<odometryTopic>odom</odometryTopic>
		</plugin>
	</gazebo>

</robot>

